--Generated by PUA : https://github.com/dean2191/PascalLove2D 
local size =  5 
 1 
var a1 
var a2 
function PythagorasFunc 
 
 PythagorasFuncD A1 A2 B1 B2 
end

function adder 
 
var b3 
block 
for  1 size b[i] i a[i] i b[i] i 
end

block 
for  1 size a[i] i i 
for  1 size a[i] i a a 
for  1 size a[i] i 