--Generated by PUA : https://github.com/dean2191/PascalLove2D 
function programadd(input,output); 
a1 
a2 
function PythagorasFunc 
 
 PythagorasFuncD A1 A2 B1 B2 
end

function adder 
 
b3 size b[i] i a[i] i b[i] i 
end

end
size a[i] i i size a[i] i a a size a[i] i 
end
