--Generated by PUA : https://github.com/dean2191/PascalLove2D 
local size 
var a1 
var a2 
function PythagorasFunc 
 
 PythagorasFuncD SQRT(A1*A2+B1*B2)A1*A2+B1*B2A1 A2 B1 B2 
end

function adder 
 
var b3 
block 
for 1sizesize b[i] ii a[i]+b[i]a[i] ii b[i] ii 
end

block 
for 1sizesize a[i] ii ii 'The array before call to adder:'
for 1sizesize a[i]a[i] ii aa aa 'The array after call to adder:'
for 1sizesize a[i]a[i] ii 